ALTER TABLE events ADD COLUMN IF NOT EXISTS has_winner BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE events ADD COLUMN IF NOT EXISTS winner_id UUID REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE events ADD COLUMN IF NOT EXISTS winner_name TEXT;
CREATE INDEX IF NOT EXISTS idx_events_winner_id ON events(winner_id) WHERE winner_id IS NOT NULL;
